// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHW5EocuR5-WnG3y0eoLYcpQmGz81siE',
    appId: '1:465778736601:android:cdecd999b49c7d71c62dc8',
    messagingSenderId: '465778736601',
    projectId: 'userlogin-f9145',
    storageBucket: 'userlogin-f9145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1q485fIYnO8zhQpiBRLLSZEXmxd0t-Qs',
    appId: '1:465778736601:ios:9480316306256f28c62dc8',
    messagingSenderId: '465778736601',
    projectId: 'userlogin-f9145',
    storageBucket: 'userlogin-f9145.firebasestorage.app',
    androidClientId: '465778736601-nph4u84065brkpbtv9i83mkeb00jp2ei.apps.googleusercontent.com',
    iosClientId: '465778736601-hrj7oj78hmac7b9sc01moiacors916lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh4fqb-xJvNp8hxb8LckRLXDI5ET_bC50',
    appId: '1:307654701968:web:3c56c73da96858000db915',
    messagingSenderId: '307654701968',
    projectId: 'machinetest-e9e40',
    authDomain: 'machinetest-e9e40.firebaseapp.com',
    storageBucket: 'machinetest-e9e40.firebasestorage.app',
    measurementId: 'G-T8831YRDNJ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApAWK-W8LSop6IyMguIslkmPKTbqJqTIY',
    appId: '1:465778736601:web:0d273f807a6059fac62dc8',
    messagingSenderId: '465778736601',
    projectId: 'userlogin-f9145',
    authDomain: 'userlogin-f9145.firebaseapp.com',
    storageBucket: 'userlogin-f9145.firebasestorage.app',
  );

}